// Matrice rôle × action × portée (docs/06 §3). Les tests sont générés à partir d'elle :
// chaque cellule produit au moins un cas autorisé et un cas refusé.
//
// Portées :
// - ALL   : toute ressource ;
// - SCOPE : ressources situées dans le périmètre territorial ou organisationnel du rôle ;
// - SELF  : ressources appartenant à l'acteur ;
// - NONE  : jamais.

export const ROLES = [
  "ADMIN_STATE",
  "AGENT_AGRICULTURE",
  "FARMER",
  "COOPERATIVE",
  "BUYER",
] as const;
export type RoleCode = (typeof ROLES)[number];

export const ACTIONS = [
  "farm.read",
  "farm.create",
  "farm.update",
  "farm.verify",
  "farm.archive",
  "farmer.read",
  "farmer.contact.read",
  "parcel.geometry.read",
  "analytics.read",
  "alert.read",
  "alert.create",
  "rule.manage",
  "alert.acknowledge",
  "alert.relay",
  "alert.resolve",
  "rule.simulate",
  "listing.read",
  "listing.create",
  "purchase.create",
  "user.role.grant",
  "user.npi.reveal",
  "audit.read",
] as const;
export type ActionCode = (typeof ACTIONS)[number];

export type Reach = "ALL" | "SCOPE" | "SELF" | "NONE";

export const POLICY_MATRIX: Record<RoleCode, Record<ActionCode, Reach>> = {
  ADMIN_STATE: {
    "farm.read": "ALL",
    "farm.create": "NONE",
    "farm.update": "NONE",
    "farm.verify": "NONE",
    "farm.archive": "ALL",
    "farmer.read": "ALL",
    "farmer.contact.read": "ALL",
    "parcel.geometry.read": "ALL",
    "analytics.read": "ALL",
    "alert.read": "ALL",
    "alert.create": "ALL",
    "rule.manage": "ALL",
    "alert.acknowledge": "ALL",
    "alert.relay": "ALL",
    "alert.resolve": "ALL",
    "rule.simulate": "ALL",
    "listing.read": "ALL",
    "listing.create": "NONE",
    "purchase.create": "NONE",
    "user.role.grant": "ALL",
    "user.npi.reveal": "ALL",
    "audit.read": "ALL",
  },
  AGENT_AGRICULTURE: {
    "farm.read": "SCOPE",
    "farm.create": "SCOPE",
    "farm.update": "SCOPE",
    "farm.verify": "SCOPE",
    "farm.archive": "NONE",
    "farmer.read": "SCOPE",
    "farmer.contact.read": "SCOPE",
    "parcel.geometry.read": "SCOPE",
    "analytics.read": "SCOPE",
    "alert.read": "SCOPE",
    "alert.create": "SCOPE",
    "rule.manage": "NONE",
    "alert.acknowledge": "SCOPE",
    "alert.relay": "SCOPE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "SCOPE",
    "purchase.create": "NONE",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
  },
  FARMER: {
    "farm.read": "SELF",
    "farm.create": "SELF",
    "farm.update": "SELF",
    "farm.verify": "NONE",
    "farm.archive": "NONE",
    "farmer.read": "SELF",
    "farmer.contact.read": "SELF",
    "parcel.geometry.read": "SELF",
    "analytics.read": "SCOPE",
    "alert.read": "SELF",
    "alert.create": "NONE",
    "rule.manage": "NONE",
    "alert.acknowledge": "SELF",
    "alert.relay": "NONE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "SELF",
    "purchase.create": "NONE",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
  },
  COOPERATIVE: {
    "farm.read": "SCOPE",
    "farm.create": "NONE",
    "farm.update": "NONE",
    "farm.verify": "NONE",
    "farm.archive": "NONE",
    "farmer.read": "SCOPE",
    "farmer.contact.read": "SCOPE",
    "parcel.geometry.read": "NONE",
    "analytics.read": "SCOPE",
    "alert.read": "SCOPE",
    "alert.create": "NONE",
    "rule.manage": "NONE",
    "alert.acknowledge": "SCOPE",
    "alert.relay": "NONE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "SCOPE",
    "purchase.create": "ALL",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
  },
  BUYER: {
    "farm.read": "NONE",
    "farm.create": "NONE",
    "farm.update": "NONE",
    "farm.verify": "NONE",
    "farm.archive": "NONE",
    "farmer.read": "NONE",
    "farmer.contact.read": "NONE",
    "parcel.geometry.read": "NONE",
    "analytics.read": "ALL",
    "alert.read": "NONE",
    "alert.create": "NONE",
    "rule.manage": "NONE",
    "alert.acknowledge": "NONE",
    "alert.relay": "NONE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "NONE",
    "purchase.create": "ALL",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
  },
};
