// Matrice rôle × action × portée (docs/06 §3). Les tests sont générés à partir d'elle :
// chaque cellule produit au moins un cas autorisé et un cas refusé.
//
// Portées :
// - ALL   : toute ressource ;
// - SCOPE : ressources situées dans le périmètre territorial ou organisationnel du rôle ;
// - SELF  : ressources appartenant à l'acteur (compte du producteur) ;
// - OWN   : ressources enregistrées par l'acteur (agent : farm.registeredById) ;
// - NONE  : jamais.

export const ROLES = [
  "ADMIN_STATE",
  "AGENT_AGRICULTURE",
  "FARMER",
  "COOPERATIVE",
  "BUYER",
] as const;
export type RoleCode = (typeof ROLES)[number];

export const ACTIONS = [
  "farm.read",
  "farm.create",
  "farm.update",
  "farm.verify",
  "farm.archive",
  "farmer.read",
  "farmer.contact.read",
  "parcel.geometry.read",
  "analytics.read",
  "alert.read",
  "alert.create",
  "rule.manage",
  "alert.acknowledge",
  "alert.relay",
  "alert.resolve",
  "rule.simulate",
  "listing.read",
  "listing.create",
  "purchase.create",
  "user.role.grant",
  "user.npi.reveal",
  "audit.read",
  // Assistant agricole (étape 8) : poser une question, lire le journal des conversations,
  // gérer le corpus de fiches techniques.
  "assistant.ask",
  "assistant.journal.read",
  "assistant.corpus.manage",
  // Signalements de terrain (phase 0) : signaler un problème sur une parcelle, lire les
  // signalements, les confirmer ou les écarter après une visite.
  "report.create",
  "report.read",
  "report.review",
  // Palmarès nominatif des producteurs (ADR-0018) : exception volontaire au masquage des petits
  // effectifs, réservée au ministère.
  "ranking.read",
  // Demandes d'assistance « Solliciter l'État » (phase 0) : demander, lire, prendre en charge et
  // résoudre. Le ministère n'en voit que les agrégats par commune (analytics.read).
  "assistance.request",
  "assistance.read",
  "assistance.handle",
  // Palmarès public (complément d'ADR-0018) : publier les lauréats consentants ; accords que le
  // producteur donne ou retire depuis son compte (palmarès, messages WhatsApp).
  "ranking.publish",
  "consent.manage",
  // Enquête aréolaire (ADR-0033) : constater l'occupation du sol sur un point tiré, dans les
  // communes de l'agent.
  "survey.observe",
  // Statistiques agricoles officielles (ADR-0034) : importer les chiffres de la DSA ou de FAOSTAT.
  "stats.import",
] as const;
export type ActionCode = (typeof ACTIONS)[number];

export type Reach = "ALL" | "SCOPE" | "SELF" | "OWN" | "NONE";

export const POLICY_MATRIX: Record<RoleCode, Record<ActionCode, Reach>> = {
  ADMIN_STATE: {
    "farm.read": "ALL",
    "farm.create": "NONE",
    "farm.update": "NONE",
    "farm.verify": "NONE",
    "farm.archive": "ALL",
    "farmer.read": "ALL",
    "farmer.contact.read": "ALL",
    "parcel.geometry.read": "ALL",
    "analytics.read": "ALL",
    "alert.read": "ALL",
    "alert.create": "ALL",
    "rule.manage": "ALL",
    "alert.acknowledge": "ALL",
    "alert.relay": "ALL",
    "alert.resolve": "ALL",
    "rule.simulate": "ALL",
    "listing.read": "ALL",
    "listing.create": "NONE",
    "purchase.create": "NONE",
    "user.role.grant": "ALL",
    "user.npi.reveal": "ALL",
    "audit.read": "ALL",
    "assistant.ask": "ALL",
    "assistant.journal.read": "ALL",
    "assistant.corpus.manage": "ALL",
    // Le ministère voit tout et peut statuer sur un signalement qu'aucun agent ne suit
    // (exploitation auto-enregistrée par son producteur, ADR-0013).
    "report.create": "NONE",
    "report.read": "ALL",
    "report.review": "ALL",
    "ranking.read": "ALL",
    // Demandes d'assistance : le ministère n'en lit que les volumes et délais par commune.
    "assistance.request": "NONE",
    "assistance.read": "NONE",
    "assistance.handle": "NONE",
    // Publication d'un palmarès public : seulement les lauréats qui ont donné leur accord.
    "ranking.publish": "ALL",
    "consent.manage": "NONE",
    "survey.observe": "NONE",
    "stats.import": "ALL",
  },
  AGENT_AGRICULTURE: {
    // ADR-0014 : un agent ne voit que les exploitations qu'il a lui-même enregistrées — jamais
    // celles d'un collègue ni celles auto-enregistrées par un producteur — y compris à la fiche,
    // à l'historique et à la vérification. `farm.create` reste SCOPE : c'est le périmètre où il
    // a le droit d'enregistrer une nouvelle exploitation, pas ce qu'il peut ensuite en revoir.
    // `farmer.contact.read` reste SCOPE : c'est un droit distinct, pour le relais d'alerte
    // climatique à tout producteur de la commune, jamais limité à ses propres enregistrements.
    "farm.read": "OWN",
    "farm.create": "SCOPE",
    "farm.update": "OWN",
    "farm.verify": "OWN",
    "farm.archive": "NONE",
    "farmer.read": "OWN",
    "farmer.contact.read": "SCOPE",
    "parcel.geometry.read": "OWN",
    "analytics.read": "SCOPE",
    "alert.read": "SCOPE",
    "alert.create": "SCOPE",
    "rule.manage": "NONE",
    "alert.acknowledge": "SCOPE",
    "alert.relay": "SCOPE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "SCOPE",
    "purchase.create": "NONE",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
    "assistant.ask": "SCOPE",
    "assistant.journal.read": "SCOPE",
    "assistant.corpus.manage": "NONE",
    // Comme le registre (ADR-0014) : les exploitations que l'agent a enregistrées.
    "report.create": "OWN",
    "report.read": "OWN",
    "report.review": "OWN",
    "ranking.read": "NONE",
    // Demandes routées vers les agents de la commune du producteur : portée territoriale, pas OWN.
    "assistance.request": "NONE",
    "assistance.read": "SCOPE",
    "assistance.handle": "SCOPE",
    "ranking.publish": "NONE",
    "consent.manage": "NONE",
    "survey.observe": "SCOPE",
    "stats.import": "NONE",
  },
  FARMER: {
    "farm.read": "SELF",
    "farm.create": "SELF",
    "farm.update": "SELF",
    "farm.verify": "NONE",
    "farm.archive": "NONE",
    "farmer.read": "SELF",
    "farmer.contact.read": "SELF",
    "parcel.geometry.read": "SELF",
    "analytics.read": "SCOPE",
    "alert.read": "SELF",
    "alert.create": "NONE",
    "rule.manage": "NONE",
    "alert.acknowledge": "SELF",
    "alert.relay": "NONE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "SELF",
    "purchase.create": "NONE",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
    "assistant.ask": "SELF",
    "assistant.journal.read": "NONE",
    "assistant.corpus.manage": "NONE",
    "report.create": "SELF",
    "report.read": "SELF",
    "report.review": "NONE",
    "ranking.read": "NONE",
    "assistance.request": "SELF",
    "assistance.read": "SELF",
    "assistance.handle": "NONE",
    "ranking.publish": "NONE",
    // Accords du producteur sur son propre compte : messages WhatsApp, palmarès public.
    "consent.manage": "SELF",
    "survey.observe": "NONE",
    "stats.import": "NONE",
  },
  COOPERATIVE: {
    "farm.read": "SCOPE",
    "farm.create": "NONE",
    "farm.update": "NONE",
    "farm.verify": "NONE",
    "farm.archive": "NONE",
    "farmer.read": "SCOPE",
    "farmer.contact.read": "SCOPE",
    "parcel.geometry.read": "NONE",
    "analytics.read": "SCOPE",
    "alert.read": "SCOPE",
    "alert.create": "NONE",
    "rule.manage": "NONE",
    "alert.acknowledge": "SCOPE",
    "alert.relay": "NONE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "SCOPE",
    "purchase.create": "ALL",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
    "assistant.ask": "SELF",
    "assistant.journal.read": "NONE",
    "assistant.corpus.manage": "NONE",
    "report.create": "NONE",
    "report.read": "NONE",
    "report.review": "NONE",
    "ranking.read": "NONE",
    "assistance.request": "NONE",
    "assistance.read": "NONE",
    "assistance.handle": "NONE",
    "ranking.publish": "NONE",
    "consent.manage": "NONE",
    "survey.observe": "NONE",
    "stats.import": "NONE",
  },
  BUYER: {
    "farm.read": "NONE",
    "farm.create": "NONE",
    "farm.update": "NONE",
    "farm.verify": "NONE",
    "farm.archive": "NONE",
    "farmer.read": "NONE",
    "farmer.contact.read": "NONE",
    "parcel.geometry.read": "NONE",
    "analytics.read": "ALL",
    "alert.read": "NONE",
    "alert.create": "NONE",
    "rule.manage": "NONE",
    "alert.acknowledge": "NONE",
    "alert.relay": "NONE",
    "alert.resolve": "NONE",
    "rule.simulate": "NONE",
    "listing.read": "ALL",
    "listing.create": "NONE",
    "purchase.create": "ALL",
    "user.role.grant": "NONE",
    "user.npi.reveal": "NONE",
    "audit.read": "NONE",
    "assistant.ask": "NONE",
    "assistant.journal.read": "NONE",
    "assistant.corpus.manage": "NONE",
    "report.create": "NONE",
    "report.read": "NONE",
    "report.review": "NONE",
    "ranking.read": "NONE",
    "assistance.request": "NONE",
    "assistance.read": "NONE",
    "assistance.handle": "NONE",
    "ranking.publish": "NONE",
    "consent.manage": "NONE",
    "survey.observe": "NONE",
    "stats.import": "NONE",
  },
};
